tfrecord_train: /dataset/tfrecords/train*
tfrecord_eval: /dataset/tfrecords/eval*
tfrecord_test: /dataset/tfrecords/test*
network_name: mobilenet
learning_rate : 0.00005
batch_size: 128
epochs: 100
transfer_learning: true # train conv layers
#grad_cam_layers:
#  - conv1
#  - conv_pw_1
#  - conv_pw_3
#  - conv_pw_5
