tfrecord_train: /dataset/tfrecords/train*
tfrecord_eval: /dataset/tfrecords/eval*
tfrecord_test: /dataset/tfrecords/test*
network_name: vgg16
learning_rate : 0.0001
batch_size: 32
epochs: 50
transfer_learning: true # train conv layers
